"""
Django settings for sitebus project.

Generated by 'django-admin startproject' using Django 5.1.5.
Docs:
- https://docs.djangoproject.com/en/5.1/topics/settings/
- https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# load .env (לשים את הקובץ .env ליד manage.py)
load_dotenv()

# -------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# Security & core flags
# -------------------------------------------------------------------
# אל תאחסן מפתח סודי בקוד! קבע ב-ENV: SECRET_KEY=...
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-secret-key-change-me")

# DEBUG: בפרודקשן לקבוע DEBUG=False ב-ENV
DEBUG = os.getenv("DEBUG", "True") == "True"

# דומיינים מותרים (מופרדים בפסיקים). לדוגמה: "myapp.onrender.com,mydomain.com"
ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = ["https://sitebus.onrender.com"]
# -------------------------------------------------------------------
# Applications
# -------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Media storage
    "cloudinary",
    "cloudinary_storage",

    # Your app
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # אם תשתמש ב-WhiteNoise לפרודקשן, הוסף כאן:
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sitebus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # כך דג'אנגו ימצא את התבניות שב-core/templates
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sitebus.wsgi.application"

# -------------------------------------------------------------------
# Database (SQLite לפיתוח; לפרודקשן מומלץ Postgres מנוהל)
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------------
# Email (Gmail SMTP – נדרש App Password)
# -------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")  # למשל: hanativhamaher1@gmail.com
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # ה-App Password בלי רווחים
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "webmaster@localhost"
CONTACT_RECIPIENT = os.getenv("CONTACT_RECIPIENT", "hanativhamaher1@gmail.com")

# -------------------------------------------------------------------
# Cloudinary – אחסון מדיה בענן
# -------------------------------------------------------------------
# אפשר גם להשתמש במשתנה יחיד CLOUDINARY_URL=cloudinary://key:securet@cloudname
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
}
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# -------------------------------------------------------------------
# I18N / TZ
# -------------------------------------------------------------------
LANGUAGE_CODE = "he-il"
TIME_ZONE = "Asia/Jerusalem"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------
STATIC_URL = "/static/"
# קבצי סטטיק של האפליקציה (לסביבת פיתוח)
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]
# יעד איסוף סטטיק לפרודקשן (collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

# -------------------------------------------------------------------
# Security hardening for production
# -------------------------------------------------------------------
# את ההגדרות הבאות עדיף להחיל בפרודקשן בלבד:
if not DEBUG:
    # הכרחה ל-HTTPS
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"

    # Cookies מאובטחים (נשלחים רק ב-HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS – התחל מערך קטן (לדוגמה שעה) ואח"כ העלה לשנה
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True") == "True"

    # מגינים נוספים
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

# -------------------------------------------------------------------
# Default PK
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
